### ISSUE TITLE
Add meta to generated routes

### ISSUE THREAD

**Issue by zefman** [ktsn/vue-route-generator#1]
It would be useful to be able to add meta to the generated routes, a little like nuxt allows you to do with https://nuxtjs.org/api/pages-head

An use case for this feature would be autogenerating a menu containing the generated routes, and providing them with a name and description.

**Comment by zefman** [comment]
@ktsn Sorry I don't think I explained in enough detail. I didn't actually mean html meta info like the vue-meta module can provide, but the meta object that can be added to routes, [https://router.vuejs.org/guide/advanced/meta.html](https://router.vuejs.org/guide/advanced/meta.html)

The example on that page is a perfect use case for when this would be useful, so that we can create middleware that is applied to specific pages etc.

I'm proposing that when defining a page component you could add an additional function to it that would be used to generate the routes meta object:

```
export default {
  data () {
    return {
      greeting: 'Hello'
    }
  },
 routeMeta() {
   return {
      authRequired: true,
      title: 'My page'
   }
 }
}
```

which would generate the a route like:

```
export default [
  {
    name: 'name',
    path: '/the-path',
    component: () => import('the-component'),
    meta: {
      authRequired: true,
      title: 'My page'
    }
  },
]
```

Additionally it would allow you to more easily generate dynamic menus based off the generated routes by using the $router object within components. Something along the lines of this:

```
<template>
    <ul>
        <li v-for="link in menuLinks" :key="link.path"><router-link :to="link.path">{{ link.title }}</router-link></li>
    </ul>
<template>

<script>
export default {
  name: 'home',
  computed: {
    menuLinks () {
      return this.$router.options.routes[0].children.map(route => {
          return {
              path: route.path,
              title: route.meta.title
          }
      })
    }
  }
}
</script>
```

**Comment by ktsn** [comment]
Understood. I see the use case and I guess it would be useful. But I don't think we can include meta data in component options because vue-route-generator does not evaluate `.vue` file. 

I think we can define some custom block and write meta data in it as json instead.

**Comment by ktsn** [comment]
@zefman You can declare route meta data in `<route-meta>` custom block since v0.2.0.
https://github.com/ktsn/vue-route-generator#route-meta

**Comment by zefman** [comment]
@ktsn nice work thanks! Using a custom block was a great idea!
