### ISSUE TITLE
Can't resolve 'module' in './node_modules/prettier'

### ISSUE THREAD

**Issue by nitish1986** [ktsn/vue-route-generator#114]
I installed your package and included as:

    const { generateRoutes } = require('vue-route-generator');

    const code = generateRoutes({
        pages: './Pages' // Vue page component directory
    });

    console.log(code);

I'm using webpack with laravel-mix so my config file has:

    const mix = require('laravel-mix');

    const tailwindcss = require('tailwindcss');

    mix.copy('Assets/images', 'public/nits-assets/images')
        .sass('sass/app.scss', 'nits-assets/css')
        .options({
            processCssUrls: false,
            postCss: [ require('autoprefixer'), tailwindcss('./tailwind.config.js') ],
        })
        .js('app.js', 'nits-assets/js')
        .webpackConfig({
            node: {
                fs: "empty"
            },
            output: {
                publicPath: '/',
                chunkFilename: 'nits-assets/chunks/[name].[chunkhash].js',
            },
            resolve: {
                symlinks: false,
                extensions: ['.js', '.json', '.vue'],
                alias: {
                    // '@': path.resolve(__dirname)
                }
            }
        })
        .sourceMaps().version();

and I'm getting following error:

    ERROR in ./node_modules/prettier/third-party.js
    Module not found: Error: Can't resolve 'module' in './node_modules/prettier'
     @ ./node_modules/prettier/third-party.js 10:31-48
     @ ./node_modules/prettier/index.js
     @ ./node_modules/vue-route-generator/lib/template/routes.js
     @ ./node_modules/vue-route-generator/lib/index.js
     @ ./node_modules/bootstrap.js
     @ ./node_modules/app.js
     @ multi ./node_modules/app.js ./node_modules/sass/app.scss

And my package.json file looks something like this:

      "devDependencies": {
        "axios": "^0.19",
        "browser-sync": "^2.26.7",
        "browser-sync-webpack-plugin": "^2.2.2",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.13",
        "resolve-url-loader": "^3.1.0",
        "sass": "^1.26.3",
        "sass-loader": "^8.0.2",
        "tailwindcss": "^1.2.0",
        "vue": "^2.6.11",
        "vue-router": "^3.1.6",
        "vue-template-compiler": "^2.6.11"
      },
      "dependencies": {
        "babel-plugin-syntax-dynamic-import": "^6.18.0",
        "laravel-mix-alias": "^1.0.2",
        "path-exists": "^4.0.0",
        "vue-route-generator": "^0.4.3",
        "vuex": "^3.1.3"
      }

Help me out in configuring it. Thanks.

**Comment by ktsn** [comment]
Thank you for filing the issue.
Please provide a minimal and self-contained reproduction to confirm the issue.

See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nitish1986** [comment]
@ktsn Thanks for the response, I've made one git repository to share some of your minimal and self-contained reproduction. Please follow the link https://github.com/nitish1986/sample-test

**Comment by ktsn** [comment]
This library is not supposed to work on browser as it generates **a code** of routes, not a route object. You should use [vue-auto-routing](https://github.com/ktsn/vue-auto-routing) if you are using webpack.
