### ISSUE TITLE
<route-meta> You may need an additional loader to handle the result of these loaders in webpack

### ISSUE THREAD

**Issue by nitish1986** [ktsn/vue-route-generator#128]
Hi,

I'm using your plugin/package in my `webpack` setup, to use this I created a `webpack` plugin of which my code look something like this:

    const fs = require('fs');
    const { generateRoutes } = require('vue-route-generator');
    const configs = require(path.resolve('./nits.config'));

    function NitsRoutePlugin () {}

    NitsRoutePlugin.prototype.apply = function (compiler) {

        compiler.hooks.thisCompilation.tap('NitsRoutePlugin', compilation => {
            try {
                exportProjectPages();
            }
            catch (error) {
                compilation.errors.push(error);
            }
        });

    };

    function exportProjectPages() {

        //Some functionality which return the codes to be written in projectRouteCode variable. 
        //Mostly with your generateRoutes({pages: '', importPrefix: '', dynamicImport: true}) function.

        fs.writeFileSync(path.resolve(__dirname, '../Routes/project-routes.js'), projectRouteCode);

    }

    module.exports = NitsRoutePlugin;

I know you have `vue-auto-routing`  which works on `webpack` but I needed some modifications to it so I opted to go for this package. Everything works fine as desired but when I use `route-meta` as suggested in documentation I gives me error:

    ERROR  Failed to compile with 1 errors                                                                                                                                                   12:20:13 AM

     error  in ./resources/pages/dashboard.vue?vue&type=custom&index=0&blockType=route-meta

    Module parse failed: Unexpected token (3:18)
    File was processed with these loaders:
     * ./node_modules/vue-loader/lib/index.js
    You may need an additional loader to handle the result of these loaders.
    | 
    | {
    >     "requiresAuth": true
    | }
    | 

Also when I compile with `watch` functionality it goes to infinite loop of creating the file and building the webpack contents. It works perfectly fine if I don't use `route-meta` tag. Help me with this, thanks.

**Comment by ktsn** [comment]
You need to specify dummy loader for the custom block. See https://github.com/ktsn/vue-cli-plugin-auto-routing/issues/23 and https://github.com/ktsn/vue-cli-plugin-auto-routing/issues/4
