### ISSUE TITLE
Warning for Parent Routes with Children which are named

### ISSUE THREAD

**Issue by mjones2620** [ktsn/vue-route-generator#14]
I'm running into the following error: 
[vue-router] Named Route 'manage' has a default child route. When navigating to this named route (:to="{name: 'manage'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.

I'm following the Nuxt Routing conventions, but in Nuxt there is an option to specify child routes using nuxt-child, which helps get rid of this warning. I don't see that as an option in the general config for this vue auto router. Essentially, if the Parent has children, the name should be removed. Can this be added as an additional option to suppress those warnings? I'm generating the routes on each build, and don't want to have to manually remove them all.

**Comment by mjones2620** [comment]
`"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const prettier = require("prettier");
function createChildrenRoute(children) {
    return `,
    children: [${children.map(createRoute).join(',')}]`;
}
function createRoute(meta) {
    const children = !meta.children ? '' : createChildrenRoute(meta.children);
    if (meta.children) {
        const routeMeta = !meta.routeMeta
            ? ''
            : ',\nmeta: ' + JSON.stringify(meta.routeMeta, null, 2);
        return `
  {
    path: '${meta.path}',
    component: ${meta.specifier}${routeMeta}${children}
  }`;
    }
    else {
        const routeMeta = !meta.routeMeta
            ? ''
            : ',\nmeta: ' + JSON.stringify(meta.routeMeta, null, 2);
        return `
  {
    name: '${meta.name}',
    path: '${meta.path}',
    component: ${meta.specifier}${routeMeta}${children}
  }`;
    }
}
function createImport(meta, dynamic) {
    const code = dynamic
        ? `const ${meta.specifier} = () => import('${meta.component}')`
        : `import ${meta.specifier} from '${meta.component}'`;
    return meta.children
        ? [code]
            .concat(meta.children.map(child => createImport(child, dynamic)))
            .join('\n')
        : code;
}
function createRoutes(meta, dynamic) {
    const imports = meta.map(m => createImport(m, dynamic)).join('\n');
    const code = meta.map(createRoute).join(',');
    return prettier.format(`${imports}\n\nexport default [${code}]`, {
        parser: 'babylon',
        semi: false,
        singleQuote: true
    });
}
exports.createRoutes = createRoutes;
`

this would fix it too.

**Comment by ktsn** [comment]
Fixed via v0.3.3
