### ISSUE TITLE
Omit index in route name

### ISSUE THREAD

**Issue by SheanDe** [ktsn/vue-route-generator#143]
Hi!

First of, thanks for the awesome job on this project!

The naming of nested route and required params route are not the same as in nuxt routing. 
The name of the file `index.vue` is added in some case to the route name and i don't think it's the expected behavior

For nested route, this structure:
```
pages/
--| users/
-----| index.vue
--| users.vue
```
will generate:
```js
routes: [
    {
      path: '/users',
      component: 'pages/users.vue',
      children: [
        {
          path: '',
          component: 'pages/users/index.vue',
          name: 'users-index'     //<--- index is added to the name
        }
      ]
    }
  ]
```
and i think it should generate the following:
```js
routes: [
    {
      path: '/users',
      component: 'pages/users.vue',
      children: [
        {
          path: '',
          component: 'pages/users/index.vue',
          name: 'users'     // <--- No index added to the name
        }
      ]
    }
  ]
```
For reference: [https://nuxtjs.org/guide/routing/#nested-routes](https://nuxtjs.org/guide/routing/#nested-routes)

It is the same for required param route. The structure:
```
pages/
--| users/
-----| _id/
--------| index.vue
```
will generate:
```js
routes: [
    {
      path: '/users',
      component: 'pages/users.vue',
      children: [
        {
          path: '/:id',
          component: 'pages/users/_id/index.vue',
          name: 'users-id-index'     //<--- index is added to the name
        }
      ]
    }
  ]
```
and i think it should generate the following:
```js
routes: [
    {
      path: '/users',
      component: 'pages/users.vue',
      children: [
        {
          path: '/:id',
          component: 'pages/users/_id/index.vue',
          name: 'users-id'     //<--- No index added to the name
        }
      ]
    }
  ]
```

I know it can be a breaking change, but i think the `index` is not required in the generated route name and it make more work to migrate from or to nuxt.

**Comment by ktsn** [comment]
Thanks. It's changed from v0.5.0
