### ISSUE TITLE
Nested routing

### ISSUE THREAD

**Issue by fagcinsk** [ktsn/vue-route-generator#16]
Hello!

What about @/pages/users/index.vue if I add that component into pages tree structure following your readme?

In nuxt that generates route with empty path, which loads as default.

ex.: https://nuxtjs.org/guide/routing/#dynamic-nested-routes

**Comment by ktsn** [comment]
What do you mean by that? vue-route-generator should behave as the same as nuxt routing in that case.

**Comment by fagcinsk** [comment]
Sorry, @ktsn my bad. For some reason --watch not resolved new index.vue file. After some changes in another file, got right routing.
