### ISSUE TITLE
using a container for most routes, how to exclude it from route path?

### ISSUE THREAD

**Issue by mariusa** [ktsn/vue-route-generator#213]
Hi,

Thanks for this useful package!
I'm using a container for **most** (but not all) routes, to avoid repeating header/footer etc in every page.
When they were set manually, it looked like this:

```
{
        path: '/',
        redirect: '/dashboard',
        component: container,
        children: [
            {
                path: 'dashboard',
                name: 'dashboard',
                component: dashboard,
            },
```

Browser URL was /#/dashboard

Using vue-route-generator, I created a folder "container/", which has `dashboard.vue`

The result works, but browser URL is /#/container/dashboard
(and all the other pages include "container/")

How to exclude "container/" from route path?

Thanks!

**Comment by ktsn** [comment]
You can use `nested: true` option and put generated routes under the container path.

https://github.com/ktsn/vue-route-generator#references

**Comment by mariusa** [comment]
Appreciate that! I tried it, but it gives 
```
Non-nested routes must include a leading slash character. Fix the following routes: 
- container/
- container/settings
- ... (all routes are listed)
```

I looked at how `nested` is used in the source code (https://github.com/ktsn/vue-route-generator/search?q=nested) , but don't see how to make it prefix top-level routes with a /

Generated routes look like
```
[
	{
		"path": "container",
		"children": [
			{
				"name": "container",
				"path": ""
			},			
			{
				"name": "container-settings",
				"path": "settings"
			}, 
...
       }, 
       {
		"name": "login",
		"path": "login",
		"meta": {
			"auth": false
		}
	},

```

I also tried `<route>` inside the container view, but has no effect
```
<route>
{
    "path": "/"
}
</route>
```

Probably it's obvious for you what the solution is? Thanks

**Comment by ktsn** [comment]
```js
import Container from './container.vue'
import routes from './path/to/generated/routes'

new Router({
  routes: [
    {
      path: '/',
      component: Container,
      children: routes
    }
  ]
})
```

**Comment by mariusa** [comment]
Thanks! That works, but now it adds the container to all views, instead of "most". 

Is there any way to get these routes auto-generated? Note how most pages are at "/", contained in Container, but there are also some top-level pages not wrapped in container (login).

```
[
    {
      path: '/',
      redirect: '/dashboard',
      component: Container,
      children: [
          {
              path: 'dashboard',
              name: 'Dashboard',
              component: Dashboard,
          },
          {
              path: 'items',
              component: Items,
          }
      ]
    },
    {
        path: '/register',
        component: Register,
        meta: { auth: false },
    },
    {
        path: '/login',
        component: Login,
        meta: { auth: false },
    }
]
```

If not possible, I'll stick to `/container/` prefix for most pages. Thanks

**Comment by ktsn** [comment]
You are looking for https://github.com/ktsn/vue-router-layout

**Comment by mariusa** [comment]
Thank you, yes, that works great together with vue-auto-routing!
Would be awesome to have these built into native VueRouter, these packages are so useful.
