### ISSUE TITLE
Passing dynamic params as props

### ISSUE THREAD

**Issue by mclate** [ktsn/vue-route-generator#67]
Hi. Wonder if it is possible to have page under `user/_id.vue` (that resolves to `user/:id` as expected) and within that page to have `props: ["id"]` where `id` is passed from the route params. In order to do so, one would have to set `props: true` in router path configuration. I wasn't able to find the way how to pass it in current route-generator.

**Comment by ThaDaVos** [comment]
I'm currently using a workaround for this, if you're interested, ping me

**Comment by mclate** [comment]
@ThaDaVos mind sharing it here?

**Comment by ThaDaVos** [comment]
Ofcourse, there's also a part in there when you're using VueRouterLayout (By the same developer).
In my instance I'm using the `<route-meta>` custom block to define the property which says, enable props as follows:
```HTML
<route-meta>
{
    "props": true
}
</route-meta>
```
Then based on the meta of the route I enable or disable the option as follows using a recursive function:
```Javascript
import routes from 'vue-auto-routing'
import { createRouterLayout } from 'vue-router-layout';

Vue.use(VueRouter);

const RouterLayout = createRouterLayout(layout => {
    return import(`#/layouts/${layout}.vue`);
});

function mapMeta(route) {
    if (route?.meta?.props) route.props = route.meta.props;
    if (route?.meta?.redirect) route.redirect = route.meta.redirect;

    if (route?.children && Array.isArray(route?.children)) route.children = route.children.map(mapMeta);

    return route;
}

const applicationRoutes = routes.map(mapMeta);
```

**Comment by ktsn** [comment]
You can specify the `props` route option via `<route>` custom block now. (>= v0.5.0)

**Comment by gilesbutler** [comment]
Hey @ktsn,

How do you use  [function mode](https://router.vuejs.org/guide/essentials/passing-props.html#function-mode) with the props parameter?

When I try `"props": route => ({ action: route.query.action, id: route.params.id })` I get...

```
Invalid json format of <route> content in campaign/_id.vue
Unexpected token / in JSON at position 114
```

Any ideas?

Thanks

**Comment by ktsn** [comment]
Yeah, since it's json, we cannot write a function in it. We have to implement #107 to do that.

**Comment by gilesbutler** [comment]
Ah thought so, all good thanks @ktsn.
