### ISSUE TITLE
Redirecting

### ISSUE THREAD

**Issue by MikeFielden** [ktsn/vue-route-generator#7]
What would be the best way to implement a vue-router style `redirect` similar to the question found [here](https://github.com/nuxt/nuxt.js/issues/1843)? 

I wouldn't be opposed to a tag style approach like the `meta` tag solved here https://github.com/ktsn/vue-route-generator/issues/1

**Comment by ktsn** [comment]
Since it generates a raw routes array, you can simply add a redirect route into it.

https://github.com/ktsn/vue-cli-plugin-auto-routing-example-redirect/blob/master/src/router.js#L12-L16

**Comment by erkstruwe** [comment]
You can achieve that by doing this (e. g. in a middleware function):

    middleware({ redirect, app, store }) {
        const merchantId = store.state.whatever
        redirect(
            307,
            app.router.resolve({
                name: "dashboard-merchant-merchantId",
                params: { merchantId },
            }).href
        )
    },
